# Generated by Django 5.0.2 on 2024-02-27 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_form'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form',
        ),
    ]
