# Generated by Django 5.0.2 on 2024-02-28 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_form'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form',
        ),
    ]
