# Generated by Django 5.0.2 on 2024-02-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_delete_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('month', models.IntegerField()),
                ('date', models.IntegerField()),
                ('size', models.IntegerField()),
                ('flavour', models.CharField(max_length=25)),
                ('code', models.CharField(max_length=5)),
                ('description', models.TextField(max_length=50)),
            ],
        ),
    ]
