# Generated by Django 5.0.2 on 2024-03-01 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='code',
            new_name='cake_code',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='d_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='description',
            new_name='d_description',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='email',
            new_name='e_email',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='flavour',
            new_name='f_flavour',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='month',
            new_name='m_month',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='n_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='p_phone',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='size',
            new_name='s_size',
        ),
    ]
