# Generated by Django 5.0.2 on 2024-03-01 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_rename_code_order_cake_code_rename_date_order_d_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cake_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='d_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='d_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='e_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='f_flavour',
            new_name='flavour',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='m_month',
            new_name='month',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='n_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='p_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='s_size',
            new_name='size',
        ),
    ]
