# Generated by Django 5.0.2 on 2024-03-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_rename_cake_code_order_code_rename_d_date_order_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('month', models.IntegerField()),
                ('date', models.IntegerField()),
                ('size', models.IntegerField()),
                ('flavour', models.CharField(max_length=25)),
                ('code', models.CharField(max_length=5)),
                ('description', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('month', models.IntegerField()),
                ('date', models.IntegerField()),
                ('size', models.IntegerField()),
                ('flavour', models.CharField(max_length=25)),
                ('code', models.CharField(max_length=5)),
                ('description', models.TextField(max_length=50)),
            ],
        ),
    ]
